AllCops:
  Include:
    - '**/Rakefile'
    - config.ru
  Exclude:
    - db/**/*
    - vendor/**/*
    - script/**/*
    - bin/**/*

  RunRailsCops: true

Documentation:
  Enabled: false

LineLength:
  Max: 120