AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*

  RunRailsCops: true

Documentation:
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact

MethodLength:
  Enabled: false
  Severity: warning
