language: ruby
cache: bundler
rvm:
- 2.1.5
services:
- memcached
env:
  global:
  - AMAZON_S3_BUCKET=cruglobal_bundle_cache
  - AMAZON_ACCESS_KEY_ID=AKIAJMC5POUXHVSOZ4XA
  - secure: B95omo/R1Jddftpp1aFxTjJuFwjJCuZ0qSuKFleRn+GKpNuOk1tze7wPp2cslLhDug7ff+ps1ELh+qjWDqSEbAZKq9mpMWu1tY1HCMEM/1AhUlk+kAXxd/arTt8bO2OjIDaylCItf8ZmhX5K/FOqV0BQMLzDR+Hx/UOyhpeHAJ8=
  - base_url=watchthinkchat.com
  - SECRET_KEY_BASE=gopgfkgokghojkghjp345jb6kjb45jkb
  - RAILS_ENV=test
  - growthspaces_access_id=MQ==
  - secure: "dNTY7Cat17U7zW/L1tIeZZPZeOjMH6rzE23rZtgFm4wOHoOIO1dkNtWLmGX2QrfzPQ8iI5If2ZJp7jVrU1TmHyy5ZMWy0eMPJb3P+bVM7LR0AiVUxQ7WoM85uyc3dkTZtnYuQ+6WNtseMOq56VwZujwVAmkM1Lt7bJ35Pj6skxU="
  - secure: hTAW1DdfaRLXqXCuMJ7kdjxWqxFL5WAFnrAS5knEmf7QfACJ9OJq97om7IFpmc2ClT1SjgwOCDgJegOvIyWK4mCWzUNgExibv+Pf2Ms9SUK1aS8P4mRKj2Oy/FuvOPBDfQjHL6Dkley6iHRiq2H8b4fonSVSbPjwot56nUpihas=
  - secure: R+oytcnLjaVzYA2EYI1NRog9eW0jW5X6DF/M80fRNLZHnFU+y7GFG0VCHoDBPE9OQyWmNCWLm05Wm0IFjG9uWcsCUaSvmbBTsT+iRe4NxtYLfeAS+9+qmv6bHggcmDPDCg8/v7exLSkddENll4FvFDIUhnqwgjVwh+KL1g8qQas=
  - secure: aC5Lb5WmQjIVdd/f4xUxdyI+c1mZ9/ZOUA2iN/3Vu8iO3q83GUrddkRizN5qMlqoV1ZfOAShVN9DUAKk8VSzaYbKpxYxgUVWjQW1IOn1l96uQdXnFVIkXX2YnSf64RsJYb0mQJ0p9X5gnSVbGJBi4P01clL4pXSGnVKvd1Zd8oM=
install:
- travis_retry script/cached-bundle install --deployment --without development
before_script:
- psql -c 'create database watchthinkchat_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:migrate RAILS_ENV=test
script:
- bin/rspec
- bundle exec rubocop
addons:
  code_climate:
    repo_token:
      secure: "Rxg/++pSjqfTBvALdk2egfgPPD2GuvbqXaAOashtAEjRroUzV4gPqBtVrZ8Io5h90URwTI8jNKS8mnTaXqFqsI0ndYjGtXrMIiig0ZCz7ggO0J6DyW4ptOIIl2zaJY3cPM3aWkbyMzM7v0S2pG3Cx4xT18SDG8+tZsLjmglW8Cs="
deploy:
  - provider: opsworks
    access_key_id: AKIAJJA7ZKF5VD6QZS2A
    secret_access_key:
      secure: dwYRBHsDeFOzJQiP3+N6T6cXqhHGrrFP2YKfLb6LYzkQo3tzZhVp9/mcKFCXo3m1gee/XuI0zIPqboKao8vFhPEdO89BtoIzT3VR/bGnq/MPKzprkckyrpJh3FVyzUjVQC4WkmXU9LqlYJZyIfvnNWnpaCXYTZiB45UQZXfvTFE=
    app-id: aaa46ab3-21b0-44b6-b5a2-094d3138cd74
    migrate: true
    wait-until-deployed: true
    on:
      repo: CruGlobal/watchthinkchat
      branch: master
  - provider: opsworks
    access_key_id: AKIAJJA7ZKF5VD6QZS2A
    secret_access_key:
      secure: dwYRBHsDeFOzJQiP3+N6T6cXqhHGrrFP2YKfLb6LYzkQo3tzZhVp9/mcKFCXo3m1gee/XuI0zIPqboKao8vFhPEdO89BtoIzT3VR/bGnq/MPKzprkckyrpJh3FVyzUjVQC4WkmXU9LqlYJZyIfvnNWnpaCXYTZiB45UQZXfvTFE=
    app-id: 610c4ce5-8fe8-47ee-8dc6-db873a12ae5f
    migrate: true
    wait-until-deployed: true
    on:
      repo: CruGlobal/watchthinkchat
      branch: develop
