# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d8a3043be3c25d3b0827186d5ef4d59d70b91999c71cb23eaeb2f30d00b78eece4fa2fbea2bcc4ca1350ae1611af7e7a7cfa39027cb7bf5f7e45a67629fc1ab

test:
  secret_key_base: 37e75a93487b42a4dcf27942caedc0db112baeabbb7913d5f44edbf68e5112191697b19926a51f495037a7a8f23e81877d9990a9057f82e9dbee1df20a720b71

production:
  secret_key_base: afb38e184fc694148a19a0d6995dd77d57e23c350949a0e5573c4fd70ff4d0338a72773abb6ba57f9572caeedbf62811545463a1627dfb599bb9e26558fd6173
